### ISSUE TITLE
Will you support converting from coffeescript?

### ISSUE THREAD

**Issue by yangligogogo** [jfmengels/lodash-codemods#12]

**Comment by jfmengels** [comment]
Hi @yangligogogo.
No, I will not. The tool ([jscodeshift](https://github.com/facebook/jscodeshift)) lodash-codemods uses to do the migration only works for JavaScript, and would not work for CoffeeScript.
If you know a tool that does the same thing, feel free to re-use code from this project to adapt it to CoffeeScript though.
